### ISSUE TITLE
npl Pilot File Not Recognized after re-launching

### ISSUE THREAD

**Issue by OpenRift412** [InsanityBringer/ICDP#2]
After creating a pilot file and setting all my settings, it seems it works fine while I'm playing, but as soon as I close the game and launch again, it won't recognize the file in the pilot select screen and I'm forced to re-do my settings. It does seem to have the name pre-typed in the new pilot name field though, but it doesn't really make a difference.

**Comment by InsanityBringer** [comment]
Where did you set up Neptune and what does the directory structure look like? I can't reproduce this ATM.

**Comment by OpenRift412** [comment]
> Where did you set up Neptune and what does the directory structure look like? I can't reproduce this ATM.

Actually, looking further into it, it seems like it may have something to do with conflicts with existing vanilla savegames/pilot files? I'm not entirely sure. Naming the pilot differently seemed to fix the issue. I don't know how it's detecting vanilla pilot files if they aren't even the same format.

**Comment by OpenRift412** [comment]
> > Where did you set up Neptune and what does the directory structure look like? I can't reproduce this ATM.
> 
> Actually, looking further into it, it seems like it may have something to do with conflicts with existing vanilla savegames/pilot files? I'm not entirely sure. Naming the pilot differently seemed to fix the issue. I don't know how it's detecting vanilla pilot files if they aren't even the same format.

Upon closer inspection, it seems to save the pilot file as an NPL file instead of an NPLT if the file shares the same name as an existing vanilla savegame, but the thing is, this happens regardless of if said savegame exists in the current directory. I'll put "OpenRift" and I have to hit enter twice, then I check the pilots from the change pilot window and the name is straight up just not there. Putting "Rift" doesn't let me proceed at all for some reason, but then subsequently putting "Rift2" adds both "Rift" and "Rift2" to the pilots list. I'm completely puzzled by this.
